spring:
  application:
    name: notification

  # JPA configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_updates: true
        order_inserts: true
        format_sql: true
        generate_statistics: true
        default_schema: postgres

  # Flyway configuration
  flyway:
    baseline-on-migrate: true
    enabled: true
    validate-on-migrate: true
    baseline-version: 0
    schemas: postgres

  # Kafka
  kafka:
    bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    groupId: ${KAFKA_CARD_GROUP_ID}
    clientId: ${KAFKA_CARD_CLIENT_ID}
    acksConfig: ${KAFKA_ACKS_CONFIG:all}
    retriesConfig: ${KAFKA_RETRIES_CONFIG:3}
    lingerMsConfig: ${KAFKA_LINGER_MS_CONFIG:100}
    clientDnsLookup: ${KAFKA_CLIENT_DNS_LOOKUP:use_all_dns_ips}
    batchSizeConfig: ${KAFKA_BATCH_SIZE_CONFIG:16384}
    bufferMemoryConfig: ${KAFKA_BUFFER_MEMORY_CONFIG:32768}
    autoOffsetResetConfig: ${KAFKA_AUTO_OFFSET_RESET_CONFIG:latest}

    topics:
      sms:
        name: "notification.sms"
        partitions: 3
        replicas: 1
      email:
        name: "notification.email"
        partitions: 3
        replicas: 1
      push:
        name: "notification.push"
        partitions: 1
        replicas: 1

  # Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: mirac.9187@gmail.com
    password: "vvfvxbglhwlmpyoa"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Tomcat configuration
server:
  port: 8081

app:
  firebase-config-path: "firebase-service-account.json"